### ISSUE TITLE
[REPORTIT - Cacti latest develop release] Email out broken when user is setup in BCC address

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_reportit#100]
Hi @TheWitness @netniV,

email is not sent when a user is configured as a BCC address:
![image](https://user-images.githubusercontent.com/1744639/217265374-79dcfd06-e1e4-4d0b-a828-571e0e01d644.png)

thanks a lot.

**Comment by netniV** [comment]
Please provide more detail @anarkia1976

**Comment by anarkia1976** [comment]
> Please provide more detail @anarkia1976

Hi @netniV,

sorry for the late response.

you can reproduce the problem by selecting:

* first email address --> insert it into --> To Email addresses Form.
* second email address --> insert it into --> BCC addresses Form.
* click on --> send report.
* nothing is happen.

In these scenario email is send out:

* first email address --> insert it into --> To Email addresses Form.
* leave empty --> insert it into --> BCC addresses Form.
* click on --> send report.
* mail out ok.

thanks a lot.

**Comment by TheWitness** [comment]
I still have to figure out how to use the plugin.  Can you post some screen shots of your various configuration items to give me a head start?

**Comment by anarkia1976** [comment]
> I still have to figure out how to use the plugin. Can you post some screen shots of your various configuration items to give me a head start?

Hi @TheWitness i have reported the problem in the wrong branch i think. sorry.

this is reporting tab:
![image](https://user-images.githubusercontent.com/1744639/229038862-85e127ed-e79f-4800-950e-027c007a0fa6.png)

thanks.

**Comment by TheWitness** [comment]
Reporting is not the same as ReportIt.

**Comment by netniV** [comment]
Reporting is built in, not the plugin reportit.
