### ISSUE TITLE
Reportit 500 Internal Server Error  

### ISSUE THREAD

**Issue by Mextor1** [Cacti/plugin_reportit#103]
Just wondering if there is a fix for  this issue?  I have searched everywhere and tried a few things with no luck.  From my findings it looks to be a total issue with PHP 8.1 compatibility.   Thank You in advance...

Plugin Reportit 1.1.3 Running on Cacti Version 1.2.22 PHP Version 8.1.2PHP 8.1.2-1ubuntu2.11 (cli)

Able to open: /cacti/plugins/reportit/view.php

All others pull the following error.

Sorry, we could not process your last action. Error:	500 Internal Server Error Reason:	The response to the last action was unexpected.

cacti.log

2023-04-16 13:59:09 - ERROR PHP ERROR: Uncaught ValueError: Unknown format specifier "a" in /var/www/html/cacti/include/global_languages.php:523 Stack trace: #0 /var/www/html/cacti/include/global_languages.php(523): sprintf() #1 /var/www/html/cacti/plugins/reportit/lib/const_reports.php(356): __() #2 /var/www/html/cacti/plugins/reportit/reports.php(36): include_once('...') #3 {main} thrown in file: /var/www/html/cacti/include/global_languages.php on line: 523

apache2 error log

[Sun Apr 16 09:59:09.721594 2023] [php:error] [pid 3650200] [client x.x.x.x.80:62441] PHP Fatal error:  Uncaught ValueError: Unknown format specifier "a" in /var/www/html/cacti/include/global_languages.php:523\nStack trace:\n#0 /var/www/html/cacti/include/global_languages.php(523): sprintf()\n#1 /var/www/html/cacti/plugins/reportit/lib/const_reports.php(356): __()\n#2 /var/www/html/cacti/plugins/reportit/reports.php(36): include_once('...')\n#3 {main}\n  thrown in /var/www/html/cacti/include/global_languages.php on line 523, referer: http://x.x.x.x/cacti/index.php

![error](https://user-images.githubusercontent.com/130938020/232347964-877bd52c-9a33-4c28-9b9e-5ecd50f07b06.jpg)

php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

**Comment by TheWitness** [comment]
Can you upgrade to the 1.2.x branch and see if the problem continues?  This may be a language processing issue associated with your selected language.  Also, are you using the Debian installer (dpk), or a source install?

**Comment by Mextor1** [comment]
I am using Cacti 1.2.22 did you want me to move to 1.2.24?
I used a sourced install...

Thank YouDon


-----Original Message-----

**Comment by TheWitness** [comment]
Yea, please start with that.  If the problem goes away let us know.  We can continue the discussion then.

**Comment by TheWitness** [comment]
No feedback.
