### ISSUE TITLE
Fatal error: Uncaught ValueError: Unknown format specifier "a" in /var/www/cacti/include/global_languages.php:523 

### ISSUE THREAD

**Issue by manel1984** [Cacti/plugin_reportit#104]
Hello,

I've just installed reportit plugin 1.1.3, my cacti version is 1.2.23 and php version PHP 8.1.2-1ubuntu2.11 

When I click on Templates--->Reports there is a fatal error and I can't configure any report.

Fatal error: Uncaught ValueError: Unknown format specifier "a" in /var/www/cacti/include/global_languages.php:523 Stack trace: #0 /var/www/cacti/include/global_languages.php(523): sprintf() #1 /var/www/cacti/plugins/reportit/include/global_forms.php(91): __() #2 /var/www/cacti/plugins/reportit/templates.php(37): include_once('...') #3 {main} thrown in /var/www/cacti/include/global_languages.php on line 523

Can you help me?

Best regards

Manel Pérez

**Comment by TheWitness** [comment]
What language are you using?

**Comment by TheWitness** [comment]
Also, how old a version of reportit are you running?

![image](https://github.com/Cacti/plugin_reportit/assets/1439914/344c1b88-3bd5-464e-9d61-5ec90b9425e9)

**Comment by manel1984** [comment]
Hello,
I'm using English language 
![imatge](https://github.com/Cacti/plugin_reportit/assets/38465824/cefc1e44-d7f1-4d44-b69a-0ef532d06582)

Where did you find 1.3 version?

https://github.com/Cacti/plugin_reportit/tree/develop
https://github.com/Cacti/plugin_reportit/blob/develop/INFO

Thank you in advance

**Comment by TheWitness** [comment]
1.3 is our develop branch.  Not for production presently.

You should consider updating global_languages from the 1.2.x branch.  Was Cacti installed using `apt`?

**Comment by manel1984** [comment]
No, my cacti was installed cloning master branch
Latest commit aa48e25d8 (HEAD -> master, tag: release/1.2.23, origin/master, XXXX/master) Preparing for 1.2.23 release

This is my global_languages https://github.com/Cacti/cacti/blob/master/include/global_languages.php

I think the lastest version

**Comment by TheWitness** [comment]
Check to see if there were any changes since to global_languages.php, and if so, update that file. 1.2.x branch only.

**Comment by manel1984** [comment]
It works.
Thank you very much :)
