### ISSUE TITLE
Reportit - permission denied error

### ISSUE THREAD

**Issue by syrus1006** [Cacti/plugin_reportit#111]
Hello Everyone!

I have 1.2.25 Cacti version installed, and Reportit plugin 1.1.2.
When I click on "Report" under the "Templates" menu, I get the "401 permission denied" error.
Also in the logs, I get several "PLUGIN WARNING: Plugin 'reportit' is attempting to call 'api_plugin_register_realm' improperly in function 'reportit_config_arrays' messages.

I tried to reinstall the plugin, but the issue is still there. Also, I can see that others have Reportit version 1.1.3., but I could not find this version anywhere.

**Comment by xmacan** [comment]
actual version is here https://github.com/Cacti/plugin_reportit  (green button "code"). Try your issue with 1.1.3 and let us know

**Comment by xmacan** [comment]
it was fixed in 2023 in 1.1.3 version
