### ISSUE TITLE
Cacti 1.1.35 and ReportIt 1.0

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_reportit#12]
I downloaded develop version and have to rename lib dir to lib_int to get it working.

**Comment by netniV** [comment]
Hi @Cramin,

The only reason you would need to rename lib to lib_int is if you are using the wrong set of PHP files/plugin.  lib_int was renamed to lib for 1.0.0 which is Cacti 1.1.7 and above compatible.

As a result I'm going to close this.  When performing any upgrade from Cacti 0.8.x with plugin 0.7.5 or below, you need to remove all sources before copying in the new ones.
