### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by JaseMac** [Cacti/plugin_reportit#120]
Hello - Hoping for some help here.

I'm setting up a new Cacti Server to replace an old working installation.

New Windows Server 2022 using the package download of Cacti-1.2.27 and upgraded to 1.2.28 with the download from cacti.net
Cacti 1.2.28
RRD 1.8.0
PHP 8.1.16
MySQL 8.0.32
Thold 1.8.2 (downloaded from GitHub)
ReportIT 1.1.4 (downloaded from GitHub)

I have all the basics working fine and now putting in the plugins. I have my basic ReportIT report for interfaces in testing however when I run the report I get the following error log and the report crashes:

2024/11/07 14:39:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024/11/07 14:39:02 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: int - string in C:\Apache24\htdocs\cacti\plugins\reportit\lib\funct_runtime.php:559 Stack trace: #0 C:\Apache24\htdocs\cacti\plugins\reportit\runtime.php(522): transform() #1 C:\Apache24\htdocs\cacti\plugins\reportit\run.php(78): runtime() #2 C:\Apache24\htdocs\cacti\plugins\reportit\run.php(55): calculation() #3 {main} thrown in file: C:\Apache24\htdocs\cacti\plugins\reportit\lib\funct_runtime.php on line: 559

More about the report:
The report is really basic to start with to make sure it worked.  The template has the traffic_in and traffic_out ds's enabled. Basic measurands for average with a calculation formulas like: f_avg*8/1000/1000

![image](https://github.com/user-attachments/assets/ff2d42ae-f178-4ddc-84f8-c3b2bafbfc49)

![image](https://github.com/user-attachments/assets/71f3c0b4-9893-4dbf-be22-4d07ca91cef9)

I've added one interface to a report using this template and try to run it.  It crashed with the errors above. 

thanks
-Jase

**Comment by TheWitness** [comment]
Update that file from the latest develop and see if the issue clears itself.  I did not write this, and I think it may have assumed that every RRDfile was valid.  This may be an edge case.  I can not dig into it too much right now.  Doing other things at the moment, but there is much more to do on this plugin.  It's some unfinished work from my perspective.

**Comment by JaseMac** [comment]
The latest develop crashes as well.  Here are the relevant logs for it:


2024/11/08 13:48:47 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024/11/08 13:48:47 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: int - string in C:\Apache24\htdocs\cacti\plugins\reportit\lib\funct_runtime.php:553 Stack trace: #0 C:\Apache24\htdocs\cacti\plugins\reportit\poller_reportit.php(590): transform() #1 C:\Apache24\htdocs\cacti\plugins\reportit\poller_reportit.php(219): runtime() #2 C:\Apache24\htdocs\cacti\plugins\reportit\poller_reportit.php(153): run() #3 {main} thrown in file: C:\Apache24\htdocs\cacti\plugins\reportit\lib\funct_runtime.php on line: 553
2024/11/08 13:42:57 - CMDPHP PHP ERROR WARNING Backtrace: (C:\Apache24\htdocs\cacti\plugins\reportit\templates.php[85]:variable_edit(), C:\Apache24\htdocs\cacti\plugins\reportit\templates.php[1877]:CactiErrorHandler())
2024/11/08 13:42:57 - ERROR PHP WARNING: Trying to access array offset on value of type null in file: C:\Apache24\htdocs\cacti\plugins\reportit\templates.php on line: 1877
2024/11/08 13:42:57 - CMDPHP PHP ERROR WARNING Backtrace: (C:\Apache24\htdocs\cacti\plugins\reportit\templates.php[85]:variable_edit(), C:\Apache24\htdocs\cacti\plugins\reportit\templates.php[1877]:CactiErrorHandler())
2024/11/08 13:42:57 - ERROR PHP WARNING: Undefined variable $variable_data in file: C:\Apache24\htdocs\cacti\plugins\reportit\templates.php on line: 1877
2024/11/08 13:41:43 - CMDPHP SQL Backtrace: (C:\Apache24\htdocs\cacti\plugins.php[78]:api_plugin_install(), C:\Apache24\htdocs\cacti\lib\plugins.php[751]:plugin_reportit_install(), C:\Apache24\htdocs\cacti\plugins\reportit\setup.php[44]:reportit_system_setup(), C:\Apache24\htdocs\cacti\plugins\reportit\setup.php[627]:reportit_system_install(), C:\Apache24\htdocs\cacti\plugins\reportit\system\install.php[374]:db_table_create(), C:\Apache24\htdocs\cacti\lib\database.php[1568]:db_execute(), C:\Apache24\htdocs\cacti\lib\database.php[420]:db_execute_prepared())
2024/11/08 13:41:43 - CMDPHP ERROR: A DB Exec Failed!, Error: Invalid default value for 'send_time'


-Jase

**Comment by TheWitness** [comment]
Okay, the 'send_time' invalid Default is a difference between MySQL and MariaDB.  Fixed that.  One of the other ones is now fixed too.  Update again, reinstall and keep breaking it!!!

**Comment by JaseMac** [comment]
This is the error when I go to install this now:
2024/11/11 10:59:07 - CMDPHP SQL Backtrace: (C:\Apache24\htdocs\cacti\plugins.php[78]:api_plugin_install(), C:\Apache24\htdocs\cacti\lib\plugins.php[751]:plugin_reportit_install(), C:\Apache24\htdocs\cacti\plugins\reportit\setup.php[44]:reportit_system_setup(), C:\Apache24\htdocs\cacti\plugins\reportit\setup.php[627]:reportit_system_install(), C:\Apache24\htdocs\cacti\plugins\reportit\system\install.php[374]:db_table_create(), C:\Apache24\htdocs\cacti\lib\database.php[1570]:db_execute(), C:\Apache24\htdocs\cacti\lib\database.php[420]:db_execute_prepared())
2024/11/11 10:59:07 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALLTER TABLE `reports_log` CHARSET = utf8mb4' at line 1


thanks
-Jase
