### ISSUE TITLE
new branch develop, cant create sql 3 TABLES

### ISSUE THREAD

**Issue by SergejLT** [Cacti/plugin_reportit#15]
my setup:
10.1.29-MariaDB
collation_server | utf8mb4_unicode_ci
character_set_client | utf8mb4

--------------------------------------------
log:
CMDPHP SQL Backtrace: (/plugins.php: 65 api_plugin_install)(/lib/plugins.php: 530 plugin_reportit_install)(/plugins/reportit/setup.php: 34 reportit_setup_table)(/plugins/reportit/setup.php: 924 db_execute)(/lib/database.php: 135 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)

CMDPHP ERROR: A DB Exec Failed!, Error: Specified key was too long; max key length is 767 bytes
DBCALL ERROR: A DB Exec Failed!, Error:1071

reportit_cache_reports
reportit_cache_measurands
reportit_cache_variables

**Comment by cigamit** [comment]
Please wait a few days.  We are waiting on a user to re-submit a pull request.  In the mean time watch the repo for the pull request and merge.

**Comment by cigamit** [comment]
Just merged the new code.  Please test again.  Close if things are better (3 tables).  Don't report new issues here.

**Comment by SergejLT** [comment]
no errors. perfect
