### ISSUE TITLE
Unable to sort data in report

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#23]
When I try to order with a column in the report, it goes back to report list (empty) and I get this error in log 

2018/06/28 15:31:49 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'traffic_in__1' in 'order clause'
--
2018/06/28 15:31:49 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:'SELECT a.*, b.description AS template_description FROM plugin_reportit_reports AS a INNER JOIN plugin_reportit_templates AS b ON b.id = a.template_id WHERE a.last_run!=0 AND a.user_id=13 ORDER BY `traffic_in__1` DESC LIMIT 0,500'

**Comment by lbsou** [comment]
Forgot to mention

Cacti 1.1.38

Latest version of reportit.

Thanks!

**Comment by lbsou** [comment]
Possible duplicate of #19, sorry

**Comment by browniebraun** [comment]
Fixed
