### ISSUE TITLE
REPORTIT ERROR: PHP modul for RRDtool is not available

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#29]
Hello,

Reportit 1.0.0
Cacti 1.1.38

I'm trying to run the report and get -> REPORTIT ERROR: PHP modul for RRDtool is not available, even if php-rrd is installed!

**Comment by netniV** [comment]
Do you have the exact message as that appears to be spelt incorrectly?  I can't seem to find that message in the code so far, so I'm wondering if there is a backtrace for this particular one?  I know you posted the other about input validation but that should have no effect on this.

**Comment by gmourani** [comment]
It's the exact message returned when running the report. See attached screenshot.

<img width="1442" alt="screen shot 2018-07-04 at 10 21 43 am" src="https://user-images.githubusercontent.com/20328799/42282388-547c9e12-7f74-11e8-9f22-c624348e7e94.png">

**Comment by netniV** [comment]
I need to learn more about ReportIT to understand where that message comes from.

**Comment by netniV** [comment]
Can you post the Technical Support information from the Console -> Utilities -> Tech Support link?  There should be a module 'php_rrdtool' enabled.  Whilst you may have the module installed, if it's not enabled it may still report the same error.

**Comment by gmourani** [comment]
Here a screenshot of the part related to retool in php-info.

<img width="827" alt="screen shot 2018-07-09 at 10 09 00 am" src="https://user-images.githubusercontent.com/20328799/42455535-80349eb6-8360-11e8-975e-e801202818e5.png">

**Comment by netniV** [comment]
It should also be visible in the Cacti Tech Support info, can you double check there too?

**Comment by gmourani** [comment]
Did you mena under the Summary tab?

<img width="408" alt="screen shot 2018-07-09 at 1 08 17 pm" src="https://user-images.githubusercontent.com/20328799/42465207-4b933ba4-8379-11e8-8436-ba78857d6a0d.png">

**Comment by browniebraun** [comment]
Today php_rrdtool is a totally different project compared to the extension from 2006. Per default Cacti uses pipeling since a while, so there is no advantage in performance by using that wrapper. One reason why I will remove that option in a timely manner.
Regards
-Andi

**Comment by browniebraun** [comment]
Options are outdated as being explained above. Removed

**Comment by eholz1** [comment]
Can anyone tell me how to get the Top Ten graphs to display? All that I get with reportit is the data display - the graphs show as vertical gray colored bars.

![cacti_reportit_sample](https://user-images.githubusercontent.com/49035408/70260613-83d24800-1745-11ea-85ff-9a5666d67728.JPG)
