### ISSUE TITLE
Management->Reports->Add  results in blank page

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_reportit#3]
Nothing in Apache error log, PHP debug log, or Cacti log.

target URL in browser nav bar is:

http://192.168.11.15/cacti/plugins/reportit/cc_reports.php?action=edit

**Comment by cigamit** [comment]
smiles,

I'm just doing the rough in right now.  This is a major redesign required to follow the new Cacti standard.

Please hold off for a few days before you bomb me with bug reports.  Rassling this puppy is going to take a good long weekend of work.  The 0.8.x design is way off.  So, there is a lot of work to do.

**Comment by smiles1969** [comment]
Noted, thanks for your hard work.

**Comment by smiles1969** [comment]
Also, on cacti/cacti #486, could the functions included in this plugin be moved to global functions since this plugin contains functions (CSV, SML and XML) for exporting already? Just a thought...

**Comment by cigamit** [comment]
smiles, browniebraun has taken over the migration.

**Comment by browniebraun** [comment]
Fixed for legacy version.
