### ISSUE TITLE
Undefined function db_install_rename_table

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_reportit#31]
The plugin was installed and working, and even had some reports being created, however it errored and disabled itself. Upon trying to re-enable the plugin, this error is thrown to the apache error log:

PHP Fatal error:  Call to undefined function db_install_rename_table() in /var/www/html/cacti/plugins/reportit/system/upgrade.php on line 44

Only place I could find that function was under cacti install so I added this to upgrade.php just to get plugin working again:

include_once('/var/www/html/cacti/install/functions.php');

**Comment by browniebraun** [comment]
Yep, that function has been moved in the meanwhile. Anyways, I will take care of that legacy version of ReportIt tonight and try to fix as much as I can before I start working again on its successor.

Regards
-Andi

**Comment by smiles1969** [comment]
Awesome! I have been hoping you would get some time to get it working.. 

It's the only thing keeping me from retiring our old cacti server running pre 1.0.

Please let me know if I can be of any assistance in this effort.

**Comment by browniebraun** [comment]
Fixed
