### ISSUE TITLE
c2v missing operator

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#33]
I'm trying to build a new operator to have a percentage over threshold value (f_dot(maxValue/8*c2v/100)) without success because c2v is missing!

Gerhard,

**Comment by browniebraun** [comment]
Have you already defined the related variable that you are trying to use here?
Regards
-Andi

**Comment by gmourani** [comment]
You're right, I've forget to create the variable first, it's work, thanks for your quick reply.
