### ISSUE TITLE
PHP Fatal error:  Call to undefined function my_id()

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#35]
Here the log in Apache log file. The screen is blank even after refresh.

[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 31, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_validate.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 31, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/funct_validate.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 31, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 32, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_shared.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 32, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/funct_shared.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 32, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 33, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_html.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 33, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/funct_html.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 33, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 34, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_online.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 34, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/funct_online.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 34, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 35, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_export.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 35, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/funct_export.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 35, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 36, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/const_view.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 36, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(): Failed opening 'REPORTIT_BASE_PATH/lib/const_view.php' for inclusion (include_path='.:/usr/share/pear:/usr/lib64/phplot:/usr/lib64/fpdf') in /var/www/html/cacti/plugins/reportit/view.php on line 36, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Fatal error:  Call to undefined function my_id() in /var/www/html/cacti/plugins/reportit/view.php on line 125, referer: https://192.168.2.227/cacti/plugins/thold/thold_graph.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Notice:  Use of undefined constant REPORTIT_BASE_PATH - assumed 'REPORTIT_BASE_PATH' in /var/www/html/cacti/plugins/reportit/view.php on line 31, referer: https://192.168.2.227/cacti/plugins/reportit/view.php
[Wed Sep 05 11:52:28 2018] [error] [client 192.168.2.147] PHP Warning:  include_once(REPORTIT_BASE_PATH/lib/funct_validate.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/reportit/view.php on line 31, referer: https://192.168.2.227/cacti/plugins/reportit/view.php

**Comment by browniebraun** [comment]
Just wondering why thold_graph.php will be listed here.

**Comment by netniV** [comment]
Because they would have been on the thold graphs page, but then clicked the reports link, thus `thold_graph.php` from thold is where they came from and `view.php` in reportit is where they were being sent.

**Comment by netniV** [comment]
I believe that this is a result of issue #36

**Comment by netniV** [comment]
Close as a duplicate of #32 since they all seem to be related

**Comment by browniebraun** [comment]
Yep, you are right regarding THOLD.
