### ISSUE TITLE
The pull down menu at the bottom of the report page work one time

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#38]
Another small bug on the report page, when choosing an action from the pull down menu at the bottom of the page, like for example provide output in text CSV format, the action complete successfully, but after if I try to select another action like output in Raw XML format or something else, the "Go" button is no longer clickable!

<img width="367" alt="screen shot 2018-09-06 at 10 49 43 am" src="https://user-images.githubusercontent.com/20328799/45165473-e7786900-b1c2-11e8-8aff-4609d78ff96a.png">

**Comment by netniV** [comment]
Are any items still selected after the action has been completed?

**Comment by netniV** [comment]
Closing do to lack of response.
