### ISSUE TITLE
Minor issue:   Console->Report Templates->Add  (Cancel Button doesn't work)

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#4]
Hi Cigamit I been watching your progress on this plugin to start testing, looks like now is a good time
I have identified a small issue  below:
Minor issue:   Console->Report Templates->Add  (Cancel Button doesn't work)  Continue button works, cancel button doesn't screenshot below:
![minor-issue](https://user-images.githubusercontent.com/11211789/27810422-044998a8-6028-11e7-90a5-b56c2f655bc1.jpeg)

Additionally I want to point errors that there are ton of php errors when I try to create and save the report as well as when I try to create a report template...

I guess you kinda aware of it and it is not yet ready for end user testing.

**Comment by browniebraun** [comment]
Fixed. More updates will follow.
