### ISSUE TITLE
When creating a new Report Template, save fails and loses all data

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_reportit#41]
Given the following configuration:
![image](https://user-images.githubusercontent.com/9052188/45166483-0b51a400-b1ef-11e8-9991-43ff71f6c37c.png)

When clicking Create, you will receive

![image](https://user-images.githubusercontent.com/9052188/45166513-1dcbdd80-b1ef-11e8-8d23-bea531c534ea.png)

Therefore, the lock should be applied by default.  The only thing I changed to make this save was to click the Locked toggle. Additionally, only Name and Additional Pre-Filter keep their settings as all other entries fields lose their settings as a result of this failure.

**Comment by ikorzha** [comment]
netniV, I was facing the same issue until i stumbled on your post.. Is there a way you can apply a fix to this problem?

**Comment by netniV** [comment]
Maybe, but I think the default was removed recently.  I will need to double check with @browniebraun on that since he's the creator/master of this ;-)

**Comment by netniV** [comment]
So, I was right, I did see a change relating to that which was 498a714 which was part of PR #16 by @Carlimeunier but it would appear that the 'locked' change is incorrect.  If @browniebraun doesn't have an update, I can look at repairing it.

**Comment by netniV** [comment]
So I went ahead and readded the automatic 'locked' status.  This should now be resolved.

**Comment by ikorzha** [comment]
netniV, can you for the fix. Can you please take a look at issue #44 
It is a next step in creating report that doesn't work in my opinion.  Looking for your advice.
