### ISSUE TITLE
Unable to add a new report in reportit: "There are no report templates available."

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#44]
I am unable to add a new report in reportit with msg: "There are no report templates available."
See the screenshot below 1:
However I do have a report template available that is published see the screenshot below 2:

Please advise

![image](https://user-images.githubusercontent.com/11211789/45901404-cb72eb00-bdb0-11e8-80fe-aee474c519b0.png)

![image](https://user-images.githubusercontent.com/11211789/45901473-04ab5b00-bdb1-11e8-9333-8eeb4572b2da.png)

**Comment by netniV** [comment]
Yes, this seems like a new issue.  I'll have to take a look shortly.

**Comment by netniV** [comment]
Well, I managed to create a report template, with the only error being that the save reported as unsuccessful but it was.

**Comment by netniV** [comment]
I believe that this issue is down to the fact you may have it on a test system and no other graphs created.  Let me know if I have that right?

**Comment by ikorzha** [comment]
No i have it installed on my prod system, same system I gave you a copy of DB from.
I didn't have an issue creating a report template, that portion worked.
Creating an actual report that is based on existing template that is what producing an error.
See original screenshot.
Please let me know if there are further questions.

**Comment by netniV** [comment]
Oh sorry, I'll go take a look at that side.

**Comment by netniV** [comment]
For a report to appear, it must be unlocked and enabled.
```sql
SELECT id, description
FROM plugin_reportit_templates
WHERE `locked` = '' AND `enabled` = 'on' ORDER BY description
```

**Comment by ikorzha** [comment]
netniV, thank you for your investigation, you are absolutely right as soon as I unlocked the template I was able to create a report.
However behavior for end user is absolutely in-intuitive. I think to avoid any questions from end users in the future it would be best to add a tip on a screenshot page I  have attached.
Stating:  "For a reportit template to appear, it must be unlocked and enabled."

I also went back and checked old version in 0.8.8x Cacti running  0.8 reportIT. Behavior is identical in new version of reportit, I am not sure why I didn't run into this problem in the old version too..

![image](https://user-images.githubusercontent.com/11211789/45918348-9ff50c80-be53-11e8-8aef-8d57c7f06c86.png)

Feel free to close this issue either with or without tip up to you :)

**Comment by netniV** [comment]
I think probably because you had a different issue... why can't I see that report? oh yeah I haven't unlocked it.

**Comment by netniV** [comment]
I have now updated the message.  Check it out and let me know what you think.

**Comment by ikorzha** [comment]
Your fix is excellent. At least now some one can make a connection between locked template and reporting.
Thank you.
![image](https://user-images.githubusercontent.com/11211789/45921239-d6e11780-be7f-11e8-987f-95d7335d9f2a.png)

**Comment by ikorzha** [comment]
netniV, there is another related issue #45 this time related to template lock. Can you please take a look when you have a chance.

**Comment by wekesa254** [comment]
Am experiencing the same problem on Cacti v1.2.26. 
![image](https://github.com/Cacti/plugin_reportit/assets/42968567/3a9e9429-4f1e-4878-b671-9adb37ae346a)

I have tried to run the above SQL command and below is the output
![image](https://github.com/Cacti/plugin_reportit/assets/42968567/8ba0e88a-ab51-48ef-8e63-54d178455e27)

**Comment by wekesa254** [comment]
Anyone online to assist

**Comment by TheWitness** [comment]
You have to create a template first.  Check under templates.  I don't know much about this plugin.  Maybe @xmacan or @browniebraun can assist.
