### ISSUE TITLE
cant run second report

### ISSUE THREAD

**Issue by SergejLT** [Cacti/plugin_reportit#48]
Created first report template that uses Data template "Interface - Traffic" and works perfect. Can run report multiple times and data is showing corectly.

When I created second report template with (same data template or diferent does not matter) and when runing report it shows nothing. 

Getting this ->

2018/09/25 08:42:36 - CMDPHP SQL Backtrace: (/plugins/reportit/view.php: 43 show_report)(/plugins/reportit/view.php: 453 get_prepared_report_data)(/plugins/reportit/lib/funct_shared.php: 120 db_fetch_assoc)(/lib/database.php: 361 db_fetch_assoc_prepared)(/lib/database.php: 402 cacti_debug_backtrace)
--
2018/09/25 08:42:36 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'traffic_in__1' in 'order clause'
2018/09/25 08:42:36 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:'SELECT a.*, b.*, c.name_cache FROM plugin_reportit_results_4 AS a INNER JOIN plugin_reportit_data_items AS b ON (a.id = b.id AND b.report_id = 4) INNER JOIN data_template_data AS c ON c.local_data_id = a.id ORDER BY **`traffic_in__1`** DESC LIMIT 0,100'

Strange when creating the second report template that uses diferent data template there is no **traffic_in** DS item. they are diferent. But in logs shows that it take this **`traffic_in__1`**

**Comment by netniV** [comment]
I believe that this is issue #18.  If after reviewing #18, you find it is the same thing, close this issue and post a comment there to be notified of updates on that thread.

**Comment by SergejLT** [comment]
closing. related to #18
