### ISSUE TITLE
"Reporting tool for Cacti" under Plugin Permissions shows multiple times

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#49]
I noticed that under Console->Users->Permissions->Reporting Tool for Cacti
Settings for Create Reports and View Reports show multiple times.
Cleanup needed...

![image](https://user-images.githubusercontent.com/11211789/46053623-a57f7a80-c111-11e8-9413-1b7cd954a2b3.png)

**Comment by netniV** [comment]
So, this is probably a REALM issue.  You likely have multiple realms for the same plugin, or the plugin is actually listed twice in the plugins table.

```sql
select * from plugin_config where directory = 'reportit'
select * from plugin_realms where plugin = 'reportit'
```

**Comment by netniV** [comment]
Did you have chance to run this query @ikorzha ?

**Comment by ikorzha** [comment]
My apologies for the delay. I suspect this doubling behavior occurs when you uninstall and re-install plugin a few times. Probably no proper cleanup by plugin is taking place...

Results are below.

![image](https://user-images.githubusercontent.com/11211789/46147377-5e89a600-c233-11e8-883e-8d8507876124.png)

**Comment by netniV** [comment]
OK so the problem here is that the upgrade has messed up because it's given you two sets of realms.  One for the old (all those cc_) and one for the new (non-cc_).  Simple answer here is to run the following query:

```sql
DELETE FROM `plugin_realms` where id in (99, 101, 102)
```

As long as you are working on with ReportIT 1.x

**Comment by ikorzha** [comment]
netniV would you believe me that they get AUTO RECREATED after I delete them under different IDs?
Can you take a look at that portion of the code in upcoming release

![image](https://user-images.githubusercontent.com/11211789/46149555-9810e000-c238-11e8-99b4-ce1dceb3715c.png)

**Comment by netniV** [comment]
This means you must have the pre-1.x code still running... check your plugins folder.

**Comment by ikorzha** [comment]
netniV I do not have pre-1.x code running. 0.8 branch isn't even compatible to install on 1.x
Not to mention my current Cacti 1.1.38 was build from ground up, I never did any migration from 0.8.8x builds.

**Comment by netniV** [comment]
Something somewhere must be running it... cc_ is only present in pre-1.x code:
```console
/usr/share/cacti/site/plugins/reportit$ grep "cc_" * -R
README.md:* bug#00089: Wrong include path in cc_graph.php
README.md:* feature: New graphic module based on "Graidle" (cc_graph has been completely
README.md:* bug#00066: Changing a lot of cc_reports.php to get more compatible to Cacti's
```

**Comment by ikorzha** [comment]
My apologies, I have realized what was happening. reportit folder in remote pollers did contain outdated reportIT files with cc_ naming convention, they were repopulating master poller plugin_realms.
I sync them manually, by deleting and re-copy from GIT and deleting entries from plugin_realm that were irrelevant. Thank you for your help in determining root cause.
