### ISSUE TITLE
report graph viewing

### ISSUE THREAD

**Issue by SergejLT** [Cacti/plugin_reportit#50]
Hello,
Using cacti v1.1.38, modern theme, new reportit plugin version.

**right clicking** on any data graph in the report I get blank new tab page (tried with firefox v62.0, and chrome v69.0.3497.100)

![reportit_2](https://user-images.githubusercontent.com/32635039/46065513-e95a9a00-c17a-11e8-8a23-ec6109d641ac.PNG)

If I **left click** directly. It shows good in the same report page.

![reportit_3](https://user-images.githubusercontent.com/32635039/46065569-13ac5780-c17b-11e8-80af-9f66b2439350.PNG)

I see paths are diferent. Any thoughts?

**Comment by netniV** [comment]
Can you paste the relative parts of the URL to the cacti base for both before and after?

**Comment by SergejLT** [comment]
https://ip/cacti/graph.php?header=false&action=zoom&local_graph_id=76940&rra_id=0&graph_start=1537822800&graph_end=1537909199

https://ip/cacti/plugins/reportit/view.php?action=show_graph_overview&id=1&rrd=101084&cache=-1

**Comment by netniV** [comment]
And which works?

**Comment by SergejLT** [comment]
This one is working
https://ip/cacti/plugins/reportit/view.php?action=show_graph_overview&id=1&rrd=101084&cache=-1

**Comment by netniV** [comment]
I am going to guess that it is purely the &header=false part that is failing for you

**Comment by SergejLT** [comment]
That did the trick. Deleted the **&header=false** and graph shown correctly.

Is it with browser or code problem?

**Comment by netniV** [comment]
Code. Unfortunately and not a lot we can do about it at this point in time as I'll have to test against multiple Cacti versions to see the best way to handle that.

**Comment by SergejLT** [comment]
ok, so editing in plugins/reportit/view.php line 897 from

> header("Location: ../../graph.php?header=false&action=zoom&local_graph_id=$local_graph_id&rra_id=0&graph_start=$start&graph_end=$end");

to

> header("Location: ../../graph.php?action=zoom&local_graph_id=$local_graph_id&rra_id=0&graph_start=$start&graph_end=$end");

got it working.

**Comment by netniV** [comment]
Yeah, but it may break in the normal process in other versions of Cacti

**Comment by netniV** [comment]
This has been fixed in 1.1.0, so look out for the release of that.
