### ISSUE TITLE
Report viewing doesn't honor separated "measurand"

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#51]
netniV, I am not sure how far along are you in 1.10 release I figured that I better bring it to your attention prior to release.
First screenshot is from ReportIt 0.8 version from Cacti .8.8x
Please notice the last set of column called "overal" and how are they segregated from traffic in and traffic out since these statistics are unified per circuit

![image](https://user-images.githubusercontent.com/11211789/46148055-3438e800-c235-11e8-99d4-4f23fd52cf55.png)

Second screenshot is from ReportIt 1.0.2 version from Cacti 1.1.38:
![image](https://user-images.githubusercontent.com/11211789/46148230-9a256f80-c235-11e8-8a16-232c4dc85813.png)

Notice there are NO overall column, and it doesn't group overall items together.

**Comment by netniV** [comment]
That might not make it into 1.1, purely because I have no idea how that works yet.  As I progress through the plugin and an old 0.6.7 manual, I'm getting a better understanding but this advanced feature is something else ;-)

**Comment by ikorzha** [comment]
I will be happy to work with you on this item once you are ready to proceed.

**Comment by ikorzha** [comment]
netniV, I actually do not believe this is a difficult issue.
Below is screenshot of one of the measurand.  Notice that it has a checkmark on "Separate"
All report needs to do is honor that field, group "separate" items together under overall column on right side of the report :)
Good news I have a working old installation we can always compare and contrast..


![image](https://user-images.githubusercontent.com/11211789/46149298-fee1c980-c237-11e8-834a-0b96f103ee89.png)

**Comment by netniV** [comment]
`all report needs to do` .... the worst words to say to a programmer ;-)

That normally means a thousand linese of code, which then get ripped out as it's not what the user wanted at all ;-)

On a more serious note, it's a totalling column (the word separate is wrong imho).  Subtotal, Total or some variation/relation thereof, would be a better description.

**Comment by ikorzha** [comment]
I laughed a lot on your comment "all reports needs to do"...

I would agree with you it is a "totaling" column, however I would defend a name that original developer described it as  "overall" it does fits best
Example: Overall circuit bandwidth 100Mbps or Overall Circuit availability 95% and so on...

**Comment by netniV** [comment]
Yes but the switch should not be separate... I don't like measurand either... in English that should be measure or measurement.  But English is my like 16th language after C++, C#, Assembly, etc....

**Comment by netniV** [comment]
This should now be resolved.
