### ISSUE TITLE
missing DB fields to save template

### ISSUE THREAD

**Issue by Amitaybi** [Cacti/plugin_reportit#57]
in table plugin_reportit_templates 2 fields are missing:
1. author
2. version

after I add manually this 2 fields, I'm able to create new templates

**Comment by netniV** [comment]
What version of reportit were you coming from?

**Comment by netniV** [comment]
Please try again with the latest development sources.  If you can also run the following SQL command before visiting the Plugin Management Page, it should run through a series of upgrades for you.

```sql
UPDATE plugin_config SET version = '1.0.2' WHERE directory = 'reportit';
```

**Comment by Amitaybi** [comment]
I use ver 1 and 1.0.1 than 1.0.2 all on top 
 without any upgrade.
Ill try it first thing in the morning. 
I also face a problem with adding email address for distribution.

**Comment by ikorzha** [comment]
First upgrade to version 1.12 current GIT development, second the email of report is currently under development by netniV, if moon and sun align me might have a solution later tonight:)

**Comment by netniV** [comment]
Follow #63 for updates on the emailing part.  It's a slightly more complex job than I had hopped.

But yes, anything less than 1.1.2 (not 1.12 😱 🙀 😨 ) will not be properly functional.  Once I have the mailing sorted, there will be  a release marker for 1.1.2 and then it'll be whatever @ikorzha, @rchen29 and @smiles1969 can dream up next.

**Comment by rchen14b** [comment]
Thank you so much for all the hard work.

**Comment by Amitaybi** [comment]
Hi. Fresh 112 is fine.
Im not able to import a template exported on 110 ver. 
Anything i can do to import it?

**Comment by netniV** [comment]
What is the problem when importing?

**Comment by netniV** [comment]
Open an issue for that as it's nothing to do with this issue.
