### ISSUE TITLE
[Feature Request]: combine two different data templates to one report template

### ISSUE THREAD

**Issue by rchen14b** [Cacti/plugin_reportit#59]
If you have data template of a radio's signal and modulation, if will be nice to combine two data source to one report, so you can view two items in that report. Currently, we can only have one data resource in a report template.

**Comment by netniV** [comment]
I've barely even begun to understand how one report works... now you want a double stack!? ;-)

I'll tag this as an enhancement but I'll be honest, I don't see me being able to do this anytime soon.  I'm slowly understanding how all this works but I'm not sure how you'd combine two different data templates.  

Maybe you could give description overview of how you'd see that working, mapping of fields etc?  ReportIT works off data template's data sources, so it already handles multiple sources of the same template.

**Comment by rchen14b** [comment]
I figured out that this can be resolved by Cacti 1.2. When support data template support SNMPGet multiple OIDs on one data source.

**Comment by netniV** [comment]
If you can post some steps here on how to do that, others may find it useful.

**Comment by rchen14b** [comment]
Hey Mark,

So I was just thinking to put two date sources in one report. With the changes of the data source template in Cacti 1.2. You can use snmpget to combine multiple OIDs in one data source which the current version only allow one OID per data source. So you can basically combine what ever data you want to one dat source by use multiple OIDs. When you create a report, you can just use all those data on that report. Not sure if that clear enough. But it just an idea to approach this. 

Regards,
Ruiyang(Ryan) Chen

**Comment by browniebraun** [comment]
That is exactly what the new version will cover, but in a different way.
Currently every report can only depend on a single Cacti data template. The next version, code has already been written (see dev branch), combines serveral data templates to groups, means you can put everything (!) within a report template. It doesn't matter if your are using different CPU templates or if you would like put interface traffic into the same on top. Something more like a universal template for all host KPIs.
Mark, we should setup a WebEx during the next days to discuss that and the future of ReportIt. I'm sorry, but I'm so busy all over the time :(

-Andi

**Comment by netniV** [comment]
Sure, you can catch me via Slack to make arrangements if you like.  I know I've probably butchered this version of ReportIT to make it work.

**Comment by rchen14b** [comment]
Thanks for the explanation. That will be very cool.

Regards,
Ruiyang(Ryan) Chen
