### ISSUE TITLE
Have issues during creat report 

### ISSUE THREAD

**Issue by Soliman2017** [Cacti/plugin_reportit#6]
Can't add report after I create template as their is no drop menu include all templates to select from it to create a report based on

**Comment by SergejLT** [comment]
same on cacti v1.1.26 and reportit v1.0

**Comment by machevalier** [comment]
Issue still present on cacti v1.1.37 and reportit v1.0. After clicking "add" to create a new report I am presented with an error "There are no report templates available."  Clicking the cancel button simply reloads the error page.

**Comment by netniV** [comment]
I believe that you need to create a template first which has to be done under `Administrate Reports`.  Once you have a template, you can then select a template to use as a base for a new report.

**Comment by browniebraun** [comment]
You have to create a report template first. After it has been unlocked you can create reports based on it.
