### ISSUE TITLE
ReportIT report view visual enhancement for readability

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#61]
netniV, first of all let me congratulate you on getting latest git 1.12 close to full functionality. There are a few items remaining that we are discussing in separate topics.
Here I would like to point out some of the visual deficiencies of the report viewing tab, the goal is to make reportit plugin build quality on par with Cacti itself.

1.  traffic_in traffic_out and overall is currently left alignment. Please have them center alignment.
2.  Please introduce a separator | between traffic_in, traffic_out and overall.
3. Please introduce a line grid for report items like it was in reportit 0.8 see screenshot below.
4. I noticed a scaling problem, if reported item description is long enough it result in report portion being lost on right hand side, In 0.8 version this is addressed by wrapping the description field. 

 
Screenshot from ReportIT 1.2: (browser zoom at 80%)
![image](https://user-images.githubusercontent.com/11211789/46449395-cff8b580-c759-11e8-81be-6952c6be720c.png)

Screenshot from ReportIT 0.8:
![image](https://user-images.githubusercontent.com/11211789/46449329-7bedd100-c759-11e8-9fd5-d7b83e6c48b7.png)

Scaling problem screenshot 3:  (browser zoom at 100%)
![image](https://user-images.githubusercontent.com/11211789/46449357-99229f80-c759-11e8-8d9b-fc8cd11f28e4.png)

**Comment by netniV** [comment]
So, the table is meant to be dynamic under cacti 1.x because it's designed to be flexible for screensizes.  That means it decides when to drop columns off (I think the browser is the one that chooses I'm not really sure).  Adding a left hand border to the subtitles is possible along with centering the text (I'd thought that too).  Line grids, again, it's the standard of cacti so that all depends on the theme you are running.

**Comment by ikorzha** [comment]
netniV please do what ever you can, I would guess item 1, item 4 and most importantly item 4...if possible.

**Comment by netniV** [comment]
OK, done what I can.  Think I've kinda addressed 3 out of 4 so 75% isn't bad ;-)

**Comment by ikorzha** [comment]
Visual fix is exceptional thank you very much. Happy with results.
