### ISSUE TITLE
Running a scheduled report via crontab doesn't work

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#64]
This issue should be addressed after issue #63 resolved as it has emailing and archiving dependency.
When I attempt to run a report from command line as this functionality existed in reportit 0.7x branch I get the following errors:

[root@CACTIONE ~]# php /var/www/html/plugins/reportit/runtime.php -d -v
PHP Fatal error:  Uncaught Error: Call to undefined function db_fetch_cell() in /var/www/html/plugins/reportit/setup.php:591
Stack trace:
#0 /var/www/html/plugins/reportit/runtime.php(43): reportit_define_constants()
#1 {main}
  thrown in /var/www/html/plugins/reportit/setup.php on line 591
[root@CACTIONE ~]#

**Comment by rchen14b** [comment]
> This issue should be addressed after issue #63 resolved as it has emailing and archiving dependency.
> When I attempt to run a report from command line as this functionality existed in reportit 0.7x branch I get the following errors:
> 
> [root@CACTIONE ~]# php /var/www/html/plugins/reportit/runtime.php -d -v
> PHP Fatal error: Uncaught Error: Call to undefined function db_fetch_cell() in /var/www/html/plugins/reportit/setup.php:591
> Stack trace:
> #0 /var/www/html/plugins/reportit/runtime.php(43): reportit_define_constants()
> #1 {main}
> thrown in /var/www/html/plugins/reportit/setup.php on line 591
> [root@CACTIONE ~]#

I tried same thing and got same result.

**Comment by netniV** [comment]
This is likely the fixes that were put in to correct the issues via the web.  There is something being applied at cli level that shouldn't.

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by ikorzha** [comment]
netniV did you do the GIT push all I see last update is for view.php to fix visual defects in report view.
I don't see any additional updates on GIT

**Comment by netniV** [comment]
Probably not, I’ll do it in the morning.

**Comment by netniV** [comment]
Pushed 👍

**Comment by ikorzha** [comment]
Looks like the fix might be a bit more involved :) just like everything else with this plugin.
I have ran a job manually, there are no longer any errors reported, However the  job doesn't see that there is a report to run...
 
[root@CACTIONE reportit]# php /var/www/html/plugins/reportit/runtime.php -d -v
2018/10/05 08:46:13 - PLUGIN REPORTIT STATS: Frequency:daily Time:0 Reports:0  Emails:0  Exports:0
[root@CACTIONE reportit]#

Lastly report doesn't show it was run as runtime is n/a after I made changes to it prior to cli run:

![image](https://user-images.githubusercontent.com/11211789/46536069-4e994400-c87b-11e8-9b72-7e93cef9a8b5.png)

**Comment by netniV** [comment]
That's a different problem, different issue number ;-)

Just kidding... likely that it's not recognising the 'on' for enabled.

**Comment by ikorzha** [comment]
I will wait for your expert diagnosis and git push...

**Comment by netniV** [comment]
I might give you average diagnosis and no git pull like last night?

**Comment by ikorzha** [comment]
netniV I will wait until Git push. I can’t utilize the potential fix until issue with email delivery and archive is resolved

**Comment by netniV** [comment]
This has now been committed to the development code.

**Comment by ikorzha** [comment]
netniV opened a separate issue 66 as the result of latest commit :)
