### ISSUE TITLE
Report for traffic now only showing overall instead of Inbound and Outbound

### ISSUE THREAD

**Issue by rchen14b** [Cacti/plugin_reportit#65]
@netniV 

Hey Mark,

Good morning. Firstly, I want thank for all your hard work recently for this plugin. It becomes more useful and stable.

I installed this new version this morning, and then the traffic report is only showing overall instead of separate Inbound and Outbound data.
![image](https://user-images.githubusercontent.com/13096569/46542880-2878a180-c885-11e8-9791-475aade54543.png)

Any ideas?

**Comment by ikorzha** [comment]
I am like you running the latest version, and have to state there NO issues with report display at all.
I suggest you examine your report template to make sure  data template checkmarks are in the right place.

![image](https://user-images.githubusercontent.com/11211789/46545090-5e248700-c893-11e8-9040-86bf3c5b42fe.png)

**Comment by rchen14b** [comment]
@ikorzha 
Ok, unchecked separate on measurand solved the issue. Thanks.

**Comment by netniV** [comment]
One thing you may not realise, if you set the same subheader for multiple sources, it will group them together and apply other sorting as appropriate.
