### ISSUE TITLE
Fix to issue #64 causing reportit plugin to error disable.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#66]
netniV, I have tested the fix for issue #64. when I run the report via cli, it causes php errors as well as "php source code display"
Report does run, but being marked as as crashed,  Lastly running report via cli causing reportit plugin to error disable.
I am attaching cli log run for your reference.
![image](https://user-images.githubusercontent.com/11211789/46566676-35cb7580-c8f1-11e8-9be7-7ae953b309c4.png)
[run-log.txt](https://github.com/Cacti/plugin_reportit/files/2452680/run-log.txt)

**Comment by netniV** [comment]
Git being a pain again, missed a load of bits.
