### ISSUE TITLE
Few errrors remaining while running report via cli & double nested export folder

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#67]
netniV, great progress on running report via cli.
I have tested the functionality. There are a couple of php errors remaining.
Lastly export feature created double nested export folder:  /var/www/html/plugins/reportit/exports/1/1/
It should have only created /var/www/html/plugins/reportit/exports/1/ folder and put report there.

Run log below:

[root@CACTIONE ~]# php /var/www/html/plugins/reportit/runtime.php -d -v
**PHP Notice:  A non well formed numeric value encountered in /var/www/html/plugins/reportit/include/vendor/pclzip/pclzip.lib.php on line 1846**
10/06/2018 09:16:38 AM - REPORTIT NOTICE: Export folder '/var/www/html/plugins/reportit/exports/1/' does not exist.
10/06/2018 09:16:38 AM - REPORTIT NOTICE: New export folder '/var/www/html/plugins/reportit/exports/1/' created.
10/06/2018 09:16:38 AM - REPORTIT NOTICE: Export folder '/var/www/html/plugins/reportit/exports/1/1/' does not exist.
10/06/2018 09:16:38 AM - REPORTIT NOTICE: New export folder '/var/www/html/plugins/reportit/exports/1/1/' created.
**PHP Notice:  Undefined index:  in /var/www/html/plugins/reportit/lib/funct_export.php on line 67
PHP Notice:  Undefined index:  in /var/www/html/plugins/reportit/lib/funct_export.php on line 68**
2018/10/06 09:16:38 - PLUGIN REPORTIT STATS: Frequency:daily Time:2.2 Reports:1  Emails:0  Exports:1
[root@CACTIONE ~]#

**Comment by netniV** [comment]
So that error would appear to be with the sub-component library to do with how much memory you are running with.  There are some debug statements I could put in, but I will see if there is an updated version that might correct it before continuing.

**Comment by ikorzha** [comment]
Sure lets see what can be done in this case.. And double nested folder too :)
