### ISSUE TITLE
.csv export performed via cli has malformed format.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#68]
netniV thank you once again for getting this plugin close to full functionality.
Today is the first time export feature is working and currently it has minor formatting flaw.
Cli export in comparison to GUI export missing all of the ";" separators.

I have attached both of the reports for your reference.

CLI Export:
[2018-10-04_2018-10-05-cli.csv.txt](https://github.com/Cacti/plugin_reportit/files/2453069/2018-10-04_2018-10-05-cli.csv.txt)
GUI Export:
[cacti_report_1-1-gui.csv.txt](https://github.com/Cacti/plugin_reportit/files/2453070/cacti_report_1-1-gui.csv.txt)

**Comment by netniV** [comment]
Do you have an example from 0.75?

**Comment by ikorzha** [comment]
Here is my log from 0.7x version, it slightly modified as header is completely removed from that version due to fact that it was causing problem in tablau further processing.
However netniV i want to point out that currently export from GUI is correct in 1.12 only automated cli export has this problem


[2018-10-05_2018-10-05.csv.log](https://github.com/Cacti/plugin_reportit/files/2453195/2018-10-05_2018-10-05.csv.log)

**Comment by netniV** [comment]
This may have majickally resolved itself with my latest commit.

**Comment by ikorzha** [comment]
My apologies, I have synced with the latest git all there was tag 1.12 I tried it but it doesn't contain any commits you have discussed.  Perhaps another sync commit is needed on your behalf :)

**Comment by netniV** [comment]
I did push it, but what happened was I missed a commit pre-check failing to commit it as it was right before bed.  Should be sorted now.

**Comment by ikorzha** [comment]
I have validated the new commit does resolve the malformed .csv export.
I will open a new issue however as when I run cli it still generates error, no email, notification and worst part it disables the plugin after cli is run..
