### ISSUE TITLE
Non well formed numeric value issued by pclzip.lib.php

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#72]
netniV, last item remaining when running report from command prompt:
PHP Notice:  A non well formed numeric value encountered in /var/www/html/plugins/reportit/include/vendor/pclzip/pclzip.lib.php on line 1846

I did some research and found I fix referenced here, I have tested the fix and it does solve the php notice errors and error in cacti log.  Can you please merge it into git development branch if allowed?

https://github.com/Piwigo/Piwigo/issues/693

Code: 
```diff
diff --git a/admin/include/pclzip.lib.php b/admin/include/pclzip.lib.php
index c2d09a5..3bb44d6 100644
--- a/admin/include/pclzip.lib.php
+++ b/admin/include/pclzip.lib.php
@@ -1836,6 +1836,7 @@
     $v_memory_limit = ini_get('memory_limit');
     $v_memory_limit = trim($v_memory_limit);
     $last = strtolower(substr($v_memory_limit, -1));
+    $v_memory_limit = intval($v_memory_limit);
  
     if($last == 'g')
```

**Comment by netniV** [comment]
Just so you know, diffs/code should be enclosed in three backticks and where possible use the code syntax highlighter name to help get things highlighted. 👍

**Comment by netniV** [comment]
This has now been committed to the development code.
