### ISSUE TITLE
Email broken for dev branch only

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_reportit#73]
There is an include statement for the phpmailer folder that is called out in lib/funct_mailer.php on line 41. 

For the master branch of cacti this works fine, however in the dev branch, the phpmailer is one folder deeper in include/vendor/

The end result is emails are not sent out if you are running the dev branch, and no log entries are generated when reports are run.

Not sure if that should be addressed in a check in the reportit plugin, or if the cacti repo should be adjusted for consistency?

**Comment by netniV** [comment]
This is a report it issue.  It should be using the old style since lib/funct_mailer.php is only used when running 1.1.38 or below.

**Comment by netniV** [comment]
I think I found the problem with the version checker code.  Can you pull the latest and retry?

**Comment by smiles1969** [comment]
Changed my include back to original, pulled the latest, and now back to no emails.

**Comment by netniV** [comment]
Is this still broken for you @smiles1969 ? Sorry, been so many things to fix lately 🗡

**Comment by smiles1969** [comment]
no, emails are still broken after I pulled the latest on 10/22

**Comment by netniV** [comment]
Can you provide any more info on how they are broken?  It's not a lot to work with especially when I can't replicate the issue.

**Comment by netniV** [comment]
For example, are you seeing the issues of #77 ?

**Comment by smiles1969** [comment]
No I am not seeing the plugin disable.

This issue itself was created on your request at the end of working issue #63 

I had emails working until I pulled the latest on Oct 22.

The only thing I'm seeing in the log when I run the report now is this:

2018/11/27 11:19:34 - WEBLOG CACTI2RRD: /usr/bin/rrdtool fetch /var/www/html/cacti/rra/metaswitch_bgfglterm_1319.rrd AVERAGE -s 1543212000 -e 1543339174
2018/11/27 11:19:34 - DBCALL ERROR: A DB Cell Failed!, Error: 1064, SQL: 'SELECT `host_snmp_cache`.`field_value` FROM `host_snmp_cache` WHERE `host_id`=2 AND `snmp_query_id`=26 AND `field_name`='bgName'  AND `snmp_index`= AND `present` > 0'

The snmp_index in the WHERE clause has no value and is throwing an error.

I'm going to delete my report and start over, will report results to this thread.

**Comment by smiles1969** [comment]
Same issue when I create a new report.

**Comment by netniV** [comment]
OK apologies, I'll review the other issue see if I can jog my memory.  The query is incorrect as you have rightly found because the index is blank.

**Comment by netniV** [comment]
OK, I'm now of the opinion that the snmp_index is related to the reindexing problems that have occurred within Cacti's core products.  Can you ensure you have the latest version of everything and see if you still have issues?

**Comment by netniV** [comment]
@smiles1969 Are you still having this issue?

**Comment by xmacan** [comment]
cannot reproduce
