### ISSUE TITLE
Error 'Constant REPORTIT_BASE_PATH already defined' appears in logs

### ISSUE THREAD

**Issue by fouadmfam** [Cacti/plugin_reportit#75]
Dears I have  Cacti V 1.1.27 and i tried to install ReportIt plugin but i have returned error in Logs.

{--2018/11/12  10:51:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_json.php: 154  rrdtool_function_graph)(/lib/rrd.php: 1241  rrd_function_process_graph_options)(/lib/rrd.php: 801  include)(/include/global_arrays.php: 1592  api_plugin_hook)(/lib/plugins.php: 73  api_plugin_run_plugin_hook)(/lib/plugins.php: 170  reportit_config_arrays)(/plugins/reportit/setup.php: 351  reportit_define_constants)(/plugins/reportit/setup.php: 600  define)(CactiErrorHandler)(/lib/functions.php: 4408  cacti_debug_backtrace)
--2018/11/12 10:51:37 - ERROR PHP NOTICE in  Plugin 'reportit':  Constant REPORTIT_BASE_PATH already defined in file:  /var/www/html/mrtg/plugins/reportit/setup.php  on line: 600}

And these messages repeated with difference Line Numbers.
i appreciate your support.

**Comment by netniV** [comment]
Have you updated to the latest version of ReportIT?

**Comment by fouadmfam** [comment]
I get the developer version. is that compatible.

**Comment by fouadmfam** [comment]
Also i downloaded v1.1.2 and get the same issue and the design of reportit tab is corrapted.

**Comment by netniV** [comment]
Redownload the latest develop version and see if that works for you.

**Comment by fouadmfam** [comment]
I re-download the latest V1.1.3 but i got the below.
1- when reportit tab appear i click it and it redirect to a white page without any theams with few links when i click console to back the reportit tab disappear and reportit change to disable in plugin management.
2-when i click log tab no result return or loaded

**Comment by netniV** [comment]
Not just the release but from develop yes?

**Comment by netniV** [comment]
Just saw that it must be.  When you get a blank page, you will likely have to refresh everything.  You should still have logs though that report issues.

**Comment by fouadmfam** [comment]
Sorry for the delay the blank page solved when restart the Apache but the error of reportit still exist.. What should I do?

**Comment by netniV** [comment]
Download th3 latest develop version

**Comment by fouadmfam** [comment]
Ok I will check and back to you.thank you

في خميس، ١٥ نوفمبر، ٢٠١٨ ٩،٠١ م Mark Brugnoli-Vinten <
notifications@github.com> كتب:
