### ISSUE TITLE
Selecting more than one report to run doesn't work

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#78]
On the reports.php page, selecting more than one report doesn't work. Only the last one on the list is run.
<img width="971" alt="screen shot 2018-11-22 at 10 21 10 am" src="https://user-images.githubusercontent.com/20328799/48911276-65522500-ee40-11e8-88db-7bb43056818b.png">

**Comment by netniV** [comment]
Only one report can be run at once via the GUI.
