### ISSUE TITLE
Issue adding recipient whilst the optional field is empty

### ISSUE THREAD

**Issue by gmourani** [Cacti/plugin_reportit#79]
Plugin reportit : 1.2.3
Cacti : 1.1.38

Just defining email address and clicking on the 'add' button doesn't work if you don't click on the [OPTIONAL] field below it to remove pre-defined text entry in the reports.php page.

<img width="966" alt="screen shot 2018-11-22 at 11 25 15 am" src="https://user-images.githubusercontent.com/20328799/48914452-80756280-ee49-11e8-85d9-5313cedcc55f.png">

Regards,

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by gmourani** [comment]
Yes, issue resolved, thanks.
