### ISSUE TITLE
syntax error, unexpected '|' in .../funct_calculate.php(531) : eval()'d code on line 1

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/plugin_reportit#84]
I am getting below error while running a particular report. Can you please check this. 
the same template is used for other reports and works fine. One particular report is giving this issue. 

```php /usr/share/cacti/plugins/reportit/runtime.php 50

 Memory:  System: 512MB    Used: 6.25MB(1.22%)   Peak: 6.37MB(1.24%)

		******* Interpretation *******
Array
(
    [0] => f_xth(95)*800/maxValue
    [1] => f_xth(95)*800/maxValue:traffic_in
    [2] => f_xth(95)*800/|query_NAN|
    [3] => f_xth(95)*800/|query_NAN|
    [4] => f_xth(95)*800/|query_NAN|
    [5] => f_xth(95)*800/|query_NAN|
    [6] => f_xth(95)*800/|query_NAN|
    [7] => f_xth( $data[$rra_index][$i], $cache[$i][2][$rra_index], 95)*800/|query_NAN|
)

PHP Parse error:  syntax error, unexpected '|' in /usr/share/cacti/plugins/reportit/lib/funct_calculate.php(531) : eval()'d code on line 1```

**Comment by netniV** [comment]
What settings do you have in place for the report?

**Comment by vishnubraj** [comment]
Below are the settings i have.. Sorry for the late responce

<img width="1270" alt="Screenshot 2019-08-08 at 3 12 39 PM" src="https://user-images.githubusercontent.com/11851188/62692865-0db81180-b9ef-11e9-91a6-52683c730b36.png">
<img width="1263" alt="Screenshot 2019-08-08 at 3 12 15 PM" src="https://user-images.githubusercontent.com/11851188/62692867-0db81180-b9ef-11e9-980e-2122d25272d0.png">
<img width="1264" alt="Screenshot 2019-08-08 at 3 11 54 PM" src="https://user-images.githubusercontent.com/11851188/62692868-0e50a800-b9ef-11e9-9a8c-b809920ab726.png">

**Comment by netniV** [comment]
Can you export the report template and upload it here?

**Comment by vishnubraj** [comment]
[reportit_templates_export_20190919_110141.xml.txt](https://github.com/Cacti/plugin_reportit/files/3630613/reportit_templates_export_20190919_110141.xml.txt)

Sorry for the late response.. Please find the attached template.. Please rename it to .xml
