### ISSUE TITLE
Upgrade from 0.7.5a to 1.1.2

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#85]
When upgrading from 0.7.5a to 1.1.2, the previous data is not imported.

**To Reproduce**

- Copy old database to a new database
- Decompress new cacti release
- Modification of config.php, etc
- Decompress new reportit version (1.1.2)

From the README : 

"After that replace your existing ReportIt folder with the new one stored in this
download archive.  Go to the plugin management console and click on "install".
The upgrade process will start automatically!  After it has finished you can
enable ReportIt with a click on "enable"."

The plugin appear as already installed and already activated.

Do I need to uninstall the old plugin first?

I tried several possibility but the table are never renamed with the "plugin_" prefix.

**Expected behavior**
Successful migration of reportit data (template, etc)

**Plugin (please complete the following information):**
 - Version: 1.1.2
 - Source: github
 - Identifer: 1.1.2 tag

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 76.0.3809.132

**Comment by netniV** [comment]
Can you be clear? Are you running Cacti 0.7.5a with ReportIt v<whatever runs on that>, and trying to go to 1.2.6 with 1.1.2 reportit?

If so, the database upgrades are only verified from 0.8.8 and above so you should upgrade to that before leaping to 1.2

**Comment by lbsou** [comment]
I'm sorry, I should have drank my coffee before writing this post.

I'm running cacti 0.8.8g with reportit 0.7.5a

I want to upgrade to cacti 1.2.6 with reportit 1.1.2.

Thanks!

**Comment by lbsou** [comment]
I executed manually the SQL commands found inside  "/plugins/reportit/system/upgrade.php" and it is now working.
