### ISSUE TITLE
Creation of report after fresh install 1.1.2 - No data source item selected

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#88]
**Describe the bug**

In the process of debugging a problem with reportit variables (that's another topic), I reinstalled reportit. I did a uninstall in the plugins module and then delete all tables plugin_reportit*.

Then, I reinstalled reportit 1.1.2. When I try to create a report template or a report, the data source is not displayed completely (no checkbox/custom name). I get a popup "No data source item selected"

This was working before the uninstall on the same version of reportit migrated/updated from reportit 0.75a.

**To Reproduce**
Install reportit from github 1.1.2 tag.

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/30626084/65621433-b87d9280-df91-11e9-9185-27b0ba817eac.png)

**Plugin (please complete the following information):**
 - Version: 1.1.2
 - Source: github
 - Identifer: 1.1.2 tag

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 77.0.3865.90

**Comment by netniV** [comment]
Is that the latest development source? If not, try that. What version of cacti are you running?

**Comment by lbsou** [comment]
Hi, I tried the latest develelopment source with same result.

I'm using Cacti 1.2.6

BUT :  I installed a brand new cacti 1.2.6 with the reportit plugin and it is working.

SO : It must be something in my database (which was upgraded from Cacti 0.8.8 / Reportit 0.7.5a

Should I start everything over (please god no) or is there some other tests I can do?

**Comment by drkrap** [comment]
Im having the exact issue:

cacti version: 1.2.6
OS: RHEL 7.0
ReportIT version: 1.1.3
Im upgrade from .0.8.8h to 1.2.6. (delete all the tables and the plugin previous to the update)


2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579721 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457
2019/09/29 22:02:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/reportit/run.php[55]:calculation(), /plugins/reportit/run.php[78]:runtime(), /plugins/reportit/runtime.php[519]:get_prepared_data(), /plugins/reportit/lib/funct_runtime.php[457]:CactiErrorHandler())
2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579719 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457
2019/09/29 22:02:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/reportit/run.php[55]:calculation(), /plugins/reportit/run.php[78]:runtime(), /plugins/reportit/runtime.php[519]:get_prepared_data(), /plugins/reportit/lib/funct_runtime.php[457]:CactiErrorHandler())
2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579717 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457

sometimes the plugin disable, but always I have the message Crashed not he report state.

**Comment by htyac** [comment]
> 
> 
> Im having the exact issue:
> 
> cacti version: 1.2.6
> OS: RHEL 7.0
> ReportIT version: 1.1.3
> Im upgrade from .0.8.8h to 1.2.6. (delete all the tables and the plugin previous to the update)
> 
> 2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579721 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457
> 2019/09/29 22:02:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/reportit/run.php[55]:calculation(), /plugins/reportit/run.php[78]:runtime(), /plugins/reportit/runtime.php[519]:get_prepared_data(), /plugins/reportit/lib/funct_runtime.php[457]:CactiErrorHandler())
> 2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579719 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457
> 2019/09/29 22:02:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/reportit/run.php[55]:calculation(), /plugins/reportit/run.php[78]:runtime(), /plugins/reportit/runtime.php[519]:get_prepared_data(), /plugins/reportit/lib/funct_runtime.php[457]:CactiErrorHandler())
> 2019/09/29 22:02:35 - ERROR PHP NOTICE in Plugin 'reportit': Undefined offset: 1579717 in file: /usr/share/cacti/plugins/reportit/lib/funct_runtime.php on line: 457
> 
> sometimes the plugin disable, but always I have the message Crashed not he report state.

I have the same issue after upgrading to Cacti 1.2.6
Please refer to Issue #87

**Comment by fouadmfam** [comment]
Dears,
i appreciate your support after i installed the latest developer version from Reportit on cacti v1.1.27, when i try to create a template i got error in logs.

2020/01/11  17:41:24 - CMDPHP SQL Backtrace: (/plugins/reportit/templates.php: 48  template_edit)(/plugins/reportit/templates.php: 697  html_template_ds_alias)(/plugins/reportit/lib/funct_html.php: 313  db_fetch_assoc_prepared)(/lib/database.php: 401 cacti_debug_backtrace)
--
2020/01/11 17:41:24 - DBCALL ERROR: SQL Assoc Failed!, Error:  Illegal mix of collations (utf8_general_ci,IMPLICIT) and  (utf8_unicode_ci,IMPLICIT) for operation '='
2020/01/11 17:41:24 - DBCALL ERROR: SQL Assoc Failed!, Error:1267,  SQL:'SELECT a.id, a.data_source_name,  b.data_source_alias, b.id AS  enabled  FROM data_template_rrd as a  LEFT JOIN (   SELECT * FROM  plugin_reportit_data_source_items WHERE template_id = ?  ) AS b  ON  a.data_source_name = b.data_source_name  WHERE a.local_data_id = 0  AND  a.data_template_id = ?'

**Comment by xmacan** [comment]
First part is duplicity of another issues. 
Illegal mix of collation is user db problem.
