### ISSUE TITLE
Unable to create variable on fresh install

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#89]
First, I want to say that reportit is an amazing report tool and i'm using it extensively. Thank you for your great work!

**Describe the bug**
Hi, 
I'm having a hard time migrating my cacti-reportit setup from 0.8.8/0.7.5a to 1.x branch as stated in issues #87 #88.

So I started over but no luck either...

I installed a brand new cacti 1.2.7 on :
CentOS Linux release 8.0.1905 (Core)
PHP 7.2.11 (cli) (built: Oct 9 2018 15:09:36) ( NTS )
MariaDB Ver 15.1 Distrib 10.3.11

and i'm unable to use a variable.

**To Reproduce**
1. Install everything from scratch
2. Create a report template
3. Inside the template, create a variable
4. Inside the template, create a measurand to see that the variable is not there.
5. Go back to variable to see that it exist.
6. Try to create another variable to obtain the error message (see screenshot).

**Expected behavior**
No need to explain :)

**Screenshots**
![image](https://user-images.githubusercontent.com/30626084/66211724-9919f000-e68a-11e9-877d-3e1b1ba4d8b2.png)

![image](https://user-images.githubusercontent.com/30626084/66211752-a505b200-e68a-11e9-82e9-b7b58c38f569.png)

**Plugin (please complete the following information):**
 - Version: develop branch
 - Source: github
 - Identifer: latest commit 8d4b6dc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90

**Comment by lbsou** [comment]
Nothing in the log...

**Comment by lbsou** [comment]
@cigamit : Jimmy, just let me know if you need anything. Are you able to reproduce on your side?

**Comment by netniV** [comment]
This will more than likely be with me, but I've just been really busy with the day job taking over my evenings so haven't had much free time.

**Comment by lbsou** [comment]
@netniV No problem Mark, I totally understand!

**Comment by drkrap** [comment]
here to! we appreciate your work!!

**Comment by netniV** [comment]
To be fair, I'm not the author, that credit goes to @browniebraun. 👍

**Comment by xmacan** [comment]
I was able to reproduce it few days ago. Now it is working well. I did a lot of changes, so probably  fixed
