### ISSUE TITLE
reportit error when saving template

### ISSUE THREAD

**Issue by Margo745** [Cacti/plugin_reportit#90]
Hi ....

I am not a programer ... and using cacti for helping me on my job ... thanks  to the developers

i have a problem with reportit plugins ... 
I get an error message when I save the reportit template

Reportit version 1.1.3

![image](https://user-images.githubusercontent.com/56357073/66497187-502cc600-eae6-11e9-9e64-e6724857283f.png)

can someone help me? thank you in advance

Cacti Version | 1.2.6
Cacti OS | unix
RSA Fingerprint | 40:a1:aa:ec:0e:eb:d1:11:36:3e:f9:81:f3:64:b6:7f
NET-SNMP Version | NET-SNMP version: 5.8
RRDtool Version Configured | 1.7.1+
RRDtool Version Found | 1.7.1

**Comment by drkrap** [comment]
possible duplicate of #88 y #89

**Comment by xmacan** [comment]
cannot reproduce with actual code
