### ISSUE TITLE
Different value in report (CLI vs WEB)

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_reportit#91]
**Describe the bug**
If report is ran from the web, result = A
If report is ran from the cli, result = B

**To Reproduce**

Run the report from web
Run the report from cli : php runtime.php <id>

**Expected behavior**
Same result

**Screenshots**

From web :  
![image](https://user-images.githubusercontent.com/30626084/69571501-2fcea300-0f90-11ea-9322-9c4fec8ed639.png)

From cli : 
![image](https://user-images.githubusercontent.com/30626084/69571545-4543cd00-0f90-11ea-8490-76ac8d481d00.png)

It just occured to me that some variable are not even produce depending of the report..

**Plugin (please complete the following information):**
 - Version: 1.1.3
 - Source: github
 - Identifer: v1.1.2-103-g8d4b6dc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78.0.3904.108

**Server (please complete the following information):**
PHP 7.3.12
Red Hat Enterprise Linux release 8.1 (Ootpa)
RRDtool 1.7.0
Cacti 1.2.7

Thank you!

**Comment by netniV** [comment]
Well, I never saw any instances of that, so it's likely related to the configuration of your report and the data you have.

**Comment by lbsou** [comment]
So your are not able to reproduce the problem?

**Comment by browniebraun** [comment]
I never had this issue, but you are not sharing your report configuration.
This would be a totally normal behavior if you have enabled flag "Up To The Day of Calculation".

**Comment by xmacan** [comment]
Agree with @browniebraun
