### ISSUE TITLE
can't create report

### ISSUE THREAD

**Issue by bet-proj** [Cacti/plugin_reportit#93]
![problem](https://user-images.githubusercontent.com/45256377/72208615-6cf1e480-34ad-11ea-925f-1f5159544811.png)
hello, 

i installed reportit plugin but i can't create a report , i have error message notification 
"**Error: No Data source item selected** " , 
and i used a cacti Version 1.1.27 
you can check attached image for error

thanks in advance

**Comment by bet-proj** [comment]
dears , 
  any update for this case ??!!!!

**Comment by netniV** [comment]
You need to add templated data sources to the report for it them to be used as variables.

**Comment by Amitaybi** [comment]
The report need ds to work on. Try to manually add interface.

**Comment by bet-proj** [comment]
how to add them 
, firstly i try to create report and then i try to add interfaces and data sources 
please clarify it by images our steps ???

**Comment by bet-proj** [comment]
Dears, 
How to add templated data sources ??? 
or
How to add ds to work on. or  manually add interface ???

**Comment by xmacan** [comment]
1) templates -> reports - create report template, enable publish, disable locked
2) management -> reports - create report from your template. Don't forget use "Add data items"
