### ISSUE TITLE
no automatic emails are sent from the report

### ISSUE THREAD

**Issue by jurix1** [Cacti/plugin_reportit#94]
hI ALL Github
I have a problem with a email automatik from reportit.
![WhatsApp Image 2020-03-15 at 10 58 36 PM](https://user-images.githubusercontent.com/62151320/76711465-a7c40300-6710-11ea-81b5-3d94c05c052a.jpeg)

**Comment by netniV** [comment]
Hi @jurix1, do you still have this issue?  Are you the one I talked through this with?
