### ISSUE TITLE
ReportIt Issues with PHP 8.1

### ISSUE THREAD

**Issue by TheWitness** [Cacti/plugin_reportit#99]
**Describe the bug**

Received a bunch of errors on PHP8.1

![image](https://user-images.githubusercontent.com/1439914/173167627-ab8cd1b5-c5b7-40d9-a5e2-9720c9087d52.png)

**Expected behavior**

Less bugs.

**Comment by lutfisan** [comment]
Has it been repaired already?

**Comment by xmacan** [comment]
cannot reproduce
